# Write your MySQL query statement below
SELECT DISTINCT S.PRODUCT_ID,FIRST_SALES.FIRST_YEAR, S.QUANTITY,S.PRICE FROM SALES S 
JOIN(SELECT PRODUCT_ID, MIN(YEAR) AS FIRST_YEAR FROM SALES GROUP BY PRODUCT_ID) 
FIRST_SALES ON S.PRODUCT_ID = FIRST_SALES.PRODUCT_ID AND S.YEAR=FIRST_SALES.FIRST_YEAR;
