# Write your MySQL query statement below
WITH FIRSTORDERS AS (SELECT CUSTOMER_ID, DELIVERY_ID, ORDER_DATE, CUSTOMER_PREF_DELIVERY_DATE, ROW_NUMBER() 
OVER( PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE) AS ORDER_RANK FROM DELIVERY) 
SELECT ROUND(100.0 * SUM(CASE WHEN ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE THEN 1 ELSE 0 END) / COUNT(*),2) 
AS IMMEDIATE_PERCENTAGE FROM FIRSTORDERS WHERE ORDER_RANK = 1;
