# Write your MySQL query statement below
SELECT PERSON_NAME FROM (SELECT PERSON_NAME, TURN, SUM(WEIGHT) 
OVER (ORDER BY TURN) AS RUNNING_WEIGHT FROM QUEUE) AS WEIGHTED_QUEUE 
WHERE RUNNING_WEIGHT<=1000 ORDER BY TURN DESC LIMIT 1;
