# Write your MySQL query statement below
WITH DAILY_TOTALS AS(SELECT VISITED_ON,SUM(AMOUNT) AS AMOUNT FROM CUSTOMER GROUP BY VISITED_ON),
MOVING_AVERAGE AS(SELECT A.VISITED_ON,SUM(B.AMOUNT) AS AMOUNT, ROUND(AVG(B.AMOUNT),2) AS AVERAGE_AMOUNT 
FROM DAILY_TOTALS A JOIN DAILY_TOTALS B ON DATEDIFF(A.VISITED_ON,B.VISITED_ON) BETWEEN 0 AND 6 GROUP BY 
A.VISITED_ON HAVING COUNT(B.VISITED_ON)=7) SELECT VISITED_ON,AMOUNT,AVERAGE_AMOUNT FROM MOVING_AVERAGE ORDER BY VISITED_ON; 
