# Write your MySQL query statement below
(SELECT U.NAME AS results FROM USERS U JOIN MOVIERATING AS MR ON U.USER_ID =  MR.USER_ID GROUP BY U.USER_ID, 
U.NAME ORDER BY COUNT(MR.MOVIE_ID) DESC, U.NAME ASC LIMIT 1) UNION ALL (SELECT M.TITLE AS results FROM MOVIES
AS M JOIN MOVIERATING AS MR ON M.MOVIE_ID = MR.MOVIE_ID WHERE MR.CREATED_AT BETWEEN '2020-02-01' AND '2020-02-29'
GROUP BY M.MOVIE_ID,M.TITLE ORDER BY AVG(MR.RATING) DESC,M.TITLE ASC LIMIT 1); 
