# Write your MySQL query statement below
SELECT R.CONTEST_ID,ROUND(COUNT(DISTINCT R.USER_ID)*100 / 
(SELECT COUNT(DISTINCT USER_ID) FROM USERS ),2) 
AS PERCENTAGE FROM REGISTER R GROUP BY R.CONTEST_ID ORDER BY PERCENTAGE DESC, R.CONTEST_ID ASC;
