# Write your MySQL query statement below
WITH RANKEDSALARIES AS (SELECT E.NAME AS EMPLOYEE,E.SALARY AS SALARY,D.NAME AS DEPARTMENT,
DENSE_RANK() OVER (PARTITION BY E.DEPARTMENTID ORDER BY E.SALARY DESC) AS SALARY_RANK FROM 
EMPLOYEE E JOIN DEPARTMENT D ON E.DEPARTMENTID=D.ID) SELECT DEPARTMENT,EMPLOYEE,SALARY FROM 
RANKEDSALARIES WHERE SALARY_RANK<=3 ORDER BY DEPARTMENT,SALARY_RANK;
