# Write your MySQL query statement below
SELECT 'Low Salary' AS category, COUNT(CASE WHEN INCOME < 20000 THEN 1 ELSE NULL END) AS 
accounts_count FROM ACCOUNTS UNION ALL SELECT 'Average Salary' AS category,
COUNT(CASE WHEN INCOME BETWEEN 20000 AND 50000 THEN 1 ELSE NULL END)  AS accounts_count 
FROM ACCOUNTS UNION ALL SELECT 'High Salary' AS category,
COUNT(CASE WHEN INCOME>50000 THEN 1 ELSE NULL END) AS accounts_count FROM ACCOUNTS ;
