# Write your MySQL query statement below
SELECT SIGNUPS.USER_ID,ROUND(IFNULL(SUM(CONFIRMATIONS.ACTION = 'CONFIRMED')/NULLIF(COUNT(CONFIRMATIONS.ACTION), 0),0),2) 
AS CONFIRMATION_RATE FROM SIGNUPS LEFT JOIN CONFIRMATIONS ON SIGNUPS.USER_ID = CONFIRMATIONS.USER_ID GROUP BY SIGNUPS.USER_ID;
