# Write your MySQL query statement below
WITH FIRSTLOGINS AS (SELECT PLAYER_ID, MIN(EVENT_DATE) AS FIRST_LOGIN FROM ACTIVITY GROUP BY PLAYER_ID), 
CONSECUTIVELOGINS AS (SELECT COUNT(DISTINCT A.PLAYER_ID) AS PLAYERS_COUNT FROM ACTIVITY A JOIN 
FIRSTLOGINS F ON A.PLAYER_ID = F.PLAYER_ID WHERE DATEDIFF(A.EVENT_DATE, F.FIRST_LOGIN) = 1), 
TOTALPLAYERS AS(SELECT COUNT(DISTINCT PLAYER_ID) AS TOTAL_COUNT FROM ACTIVITY) 
SELECT ROUND((SELECT PLAYERS_COUNT FROM CONSECUTIVELOGINS) / (SELECT TOTAL_COUNT FROM TOTALPLAYERS), 2) AS FRACTION;
