# Write your MySQL query statement below
SELECT EMPLOYEE.NAME FROM EMPLOYEE JOIN ( SELECT MANAGERID FROM EMPLOYEE WHERE MANAGERID IS NOT NULL GROUP BY MANAGERID HAVING COUNT(*) >= 5) M ON EMPLOYEE.ID = M.MANAGERID;
