# Write your MySQL query statement below
WITH FRIEND_COUNTS AS (SELECT ID, COUNT(*) AS NUM FROM (SELECT REQUESTER_ID AS ID FROM 
REQUESTACCEPTED UNION ALL SELECT ACCEPTER_ID AS ID FROM REQUESTACCEPTED) 
AS ALL_FRIENDS GROUP BY ID) SELECT ID, NUM FROM FRIEND_COUNTS WHERE 
NUM = (SELECT MAX(NUM) FROM FRIEND_COUNTS);
